### ISSUE TITLE
Not sure it was stuck or not.

### ISSUE THREAD

**Issue by kaninhot004** [HobbitDur/HobbitInstaller#1]
![image](https://github.com/user-attachments/assets/c9207feb-3f9f-4e3d-9971-54055eb968d3)

On OST-RF part. It keep stuck at 66% (I tried it 2 times and got same results)

**Comment by kaninhot004** [comment]
No problem now, just wait and it will success soon. XD

**Comment by HobbitDur** [comment]
Hi thank you for your report anyway ! I appreciate people getting interest in it.
Yes the mod is quite big, so it takes a long time especially if you don't have a good connexion (and even then tsuna server is not really fast).
Maybe I should implement an other way to say it is downloading. Normally I let the console for this reason so people know it is downloading. Maybe I will add a "BE PATIENT" 
Btw it was my first release with demaster. How it went ? I will work on removing the gui from demaster so it works flowlesly, but didn't the extra gui pose a problem to you ?

**Comment by kaninhot004** [comment]
I didn't test it yet. I will report soon.

Thank you!

**Comment by kaninhot004** [comment]
> Hi thank you for your report anyway ! I appreciate people getting interest in it. Yes the mod is quite big, so it takes a long time especially if you don't have a good connexion (and even then tsuna server is not really fast). Maybe I should implement an other way to say it is downloading. Normally I let the console for this reason so people know it is downloading. Maybe I will add a "BE PATIENT" Btw it was my first release with demaster. How it went ? I will work on removing the gui from demaster so it works flowlesly, but didn't the extra gui pose a problem to you ?

Today I just tried it.
OST-RF working fine. (Also game working fine, I just finished Ifrit part.)
For GUI I didn't knew what it does is it Text Box animation?
